// Seed data for НПО КИПРОЛ — extracted from the original one-pager, RU/EN.

const categories = [
  {
    slug: 'vie', code: '2.1', icon: '🔆',
    name_ru: 'Возобновляемые источники энергии', name_en: 'Renewable energy sources',
    note_ru: 'Солнечные панели и инверторы, ветрогенераторы, солнечные водяные коллекторы.',
    note_en: 'Solar panels and inverters, wind generators, solar water collectors.',
  },
  {
    slug: 'krm', code: '2.2', icon: '⚡',
    name_ru: 'Компенсация реактивной мощности', name_en: 'Reactive power compensation',
    note_ru: 'Изготавливаем и поставляем конденсаторные установки и батареи напряжением от 230 В до 220 кВ типов УКМ, УКМФ, УК, УКМ58, УКР(Л)56, ФКУ, БСК, в полном соответствии с ГОСТ и ТР.',
    note_en: 'We manufacture & supply capacitor units and banks rated 230 V to 220 kV of types UKM, UKMF, UK, UKM58, UKR(L)56, FKU, BSK, in full compliance with GOST and technical regulations.',
  },
  {
    slug: 'converters', code: '2.3', icon: '⟳',
    name_ru: 'Полупроводниковые преобразователи', name_en: 'Semiconductor converters',
    note_ru: 'Серийные изделия и уникальные решения, изготовленные по требованиям заказчика. Выпрямители управляемые и неуправляемые до и выше 1000 В. Специализированные преобразователи, контакторы и пускатели, КТТ, ПТТ, БАВР и другие.',
    note_en: 'Serial products and custom solutions built to customer requirements. Controlled and uncontrolled rectifiers up to and above 1000 V. Specialized converters, contactors and starters, KTT, PTT, BAVR and others.',
  },
  {
    slug: 'protection', code: '2.4', icon: '🛡',
    name_ru: 'Системы управления и защиты', name_en: 'Control & protection systems',
    note_ru: 'Регуляторы для КРМ и реле небалансной защиты БСК.',
    note_en: 'Power factor controllers and capacitor bank unbalance protection relays.',
  },
  {
    slug: 'electronics', code: '2.5', icon: '🔩',
    name_ru: 'Радиоэлектронные компоненты', name_en: 'Electronic components',
    note_ru: 'Микросхемы, пассивные компоненты, дискретные полупроводники и конденсаторы.',
    note_en: 'Integrated circuits, passive components, discrete semiconductors and capacitors.',
  },
  {
    slug: 'reactors', code: '2.6', icon: '🧲',
    name_ru: 'Электрические реакторы', name_en: 'Electric reactors',
    note_ru: 'Реакторы и дроссели, проверенные годами безаварийной эксплуатации: РТСТ, РТОС, РТЛД, РОЛД, РФСТ, РФОС.',
    note_en: 'Reactors and chokes proven by years of trouble-free operation: RTST, RTOS, RTLD, ROLD, RFST, RFOS.',
  },
  {
    slug: 'forklifts', code: '2.7', icon: '🚜',
    name_ru: 'Вилочные погрузчики и складская техника', name_en: 'Forklifts & warehouse equipment',
    note_ru: 'Дизельные, газобензиновые и электрические погрузчики, штабелеры, ричтраки, паллет-транспортировщики и другое.',
    note_en: 'Diesel, LPG/petrol and electric forklifts, stackers, reach trucks, pallet trucks and more.',
  },
  {
    slug: 'parts', code: '2.8', icon: '🔧',
    name_ru: 'Запасные части', name_en: 'Spare parts',
    note_ru: 'Запчасти промышленного оборудования, автомобилей и складской техники, аккумуляторные батареи, шины, расходные материалы.',
    note_en: 'Spare parts for industrial equipment, vehicles and warehouse machinery, battery packs, tyres, consumables.',
  },
  {
    slug: 'fluids', code: '2.9', icon: '🛢',
    name_ru: 'Технические жидкости', name_en: 'Technical fluids',
    note_ru: 'Моторные, трансмиссионные, гидравлические и индустриальные масла, охлаждающие жидкости, технологические смазки.',
    note_en: 'Engine, transmission, hydraulic and industrial oils, coolants, technical greases.',
  },
];

// [code, name_ru, name_en, desc_ru, desc_en, category_slug]
const P = (code, ru, en, dru, den, cat) => ({ code, name_ru: ru, name_en: en, description_ru: dru, description_en: den, category_slug: cat });

const products = [
  P('2.1.1', 'Солнечные панели', 'Solar panels',
    'Монокристаллические и поликристаллические фотоэлектрические панели для станций и систем на объектах заказчика.',
    'Mono- and polycrystalline photovoltaic panels for customer sites and power plants.', 'vie'),
  P('2.1.2', 'Солнечные инверторы', 'Solar inverters',
    'Инверторы для фотоэлектрических станций: сетевые и гибридные решения под конкретную мощность системы.',
    'Inverters for photovoltaic plants: grid-tied and hybrid solutions matched to system capacity.', 'vie'),
  P('2.1.3', 'Ветрогенераторы', 'Wind generators',
    'Ветрогенераторы для автономных и гибридных систем электроснабжения.',
    'Wind generators for autonomous and hybrid power supply systems.', 'vie'),
  P('2.1.4', 'Солнечные водяные коллекторы', 'Solar water collectors',
    'Солнечные водяные коллекторы для систем горячего водоснабжения и обогрева.',
    'Solar water collectors for hot water and heating systems.', 'vie'),

  P('2.2.1', 'Токоограничивающие реакторы', 'Current-limiting reactors',
    'Токоограничивающие реакторы и дроссели для конденсаторных установок компенсации реактивной мощности.',
    'Current-limiting reactors and chokes for reactive power compensation capacitor units.', 'krm'),
  P('2.2.2', 'Шунтирующие реакторы', 'Shunt reactors',
    'Шунтирующие реакторы для сетей и подстанций, выравнивание распределения реактивной мощности.',
    'Shunt reactors for networks and substations, balancing reactive power distribution.', 'krm'),
  P('2.2.3', 'Фильтровые реакторы', 'Filter reactors',
    'Фильтровые реакторы для пассивных фильтров гармоник сетей с преобразовательной техникой.',
    'Filter reactors for passive harmonic filters in networks with converter equipment.', 'krm'),
  P('2.2.4', 'Демпфирующие реакторы', 'Damping reactors',
    'Демпфирующие реакторы для подавления резонансных явлений в сетях с нелинейными нагрузками.',
    'Damping reactors for suppressing resonance in networks with non-linear loads.', 'krm'),
  P('2.2.5', 'Конденсаторы для КРМ и фильтров гармоник', 'Capacitors for KRM & harmonic filters',
    'Надёжные и стабильные плёночные конденсаторы производства Anhui Chang Rong Electronics Co. Ltd. Возможна разработка специальных плёночных конденсаторов по техническим требованиям заказчика.',
    'Reliable, stable film capacitors by Anhui Chang Rong Electronics Co. Ltd. Custom film capacitors can be developed to customer specifications.', 'krm'),
  P('2.2.6', 'Регуляторы для КРМ', 'Power factor controllers',
    'Регуляторы коэффициента мощности с многоступенчатым управлением отключаемыми ступенями конденсаторной установки.',
    'Power factor controllers with multi-step control of capacitor bank sections.', 'krm'),

  P('2.3.1', 'Активные фильтры гармоник', 'Active harmonic filters',
    'Устранение высших гармонических искажений, создаваемых нелинейными нагрузками: преобразователями и приводной техникой.',
    'Elimination of higher harmonic distortion from non-linear loads: converters and drives.', 'converters'),
  P('2.3.2', 'Конденсаторы для силовой электроники', 'Power electronics capacitors',
    'Силовые электронные плёночные конденсаторы: фильтровые конденсаторы постоянного тока, конденсаторы звена постоянного тока преобразователей, для электротранспорта.',
    'Power electronic film capacitors: DC filter capacitors, converter DC-link capacitors, electric vehicle capacitors.', 'converters'),
  P('2.3.3', 'Частотные преобразователи', 'Frequency converters',
    'Частотные преобразователи для электродвигателей и приводов, серийные и нестандартные исполнения.',
    'Frequency converters for motors and drives, standard and special variants.', 'converters'),
  P('2.3.4', 'Тиристорные пускатели и контакторы', 'Thyristor starters & contactors',
    'Выпрямители управляемые и неуправляемые до и выше 1000 В, специализированные преобразователи, контакторы и пускатели, КТТ, ПТТ, БАВР.',
    'Controlled and uncontrolled rectifiers up to and above 1000 V, specialized converters, contactors, starters, KTT, PTT, BAVR.', 'converters'),

  P('2.4.1', 'Регулирование и управление КРМ', 'KRM control & regulation',
    'Системы регулирования и управления конденсаторными установками: регуляторы коэффициента мощности, многоступенчатое управление.',
    'Control and regulation systems for capacitor units: power factor regulators, multi-step control.', 'protection'),
  P('2.4.2', 'Реле небалансной защиты БСК', 'Capacitor bank unbalance protection relays',
    'Реле небалансной защиты батарей статических конденсаторов и системы управления для БСК.',
    'Unbalance protection relays and control systems for static capacitor banks.', 'protection'),

  P('2.5.1', 'Микросхемы', 'Integrated circuits',
    'Поставка микросхем из дружественных стран: силовая и промышленная электроника.',
    'Integrated circuits supplied from friendly countries: power and industrial electronics.', 'electronics'),
  P('2.5.2', 'Пассивные компоненты', 'Passive components',
    'Резисторы, конденсаторы, дроссели и другие пассивные компоненты для промышленной электроники.',
    'Resistors, capacitors, chokes and other passive components for industrial electronics.', 'electronics'),
  P('2.5.3', 'Дискретные полупроводники', 'Discrete semiconductors',
    'Тиристоры, транзисторы, диоды и другие дискретные полупроводниковые компоненты для преобразовательной техники.',
    'Thyristors, transistors, diodes and other discrete semiconductors for power conversion equipment.', 'electronics'),
  P('2.5.4', 'Конденсаторы (радиоэлектроника)', 'Capacitors (electronics)',
    'Конденсаторы для компенсации реактивной мощности и фильтров гармоник, конденсаторы для силовой электроники.',
    'Capacitors for reactive power compensation and harmonic filters, power electronics capacitors.', 'electronics'),

  P('2.6.1', 'Токоограничивающие реакторы (РТСТ, РТЛД)', 'Current-limiting reactors (RTST, RTLD)',
    'Серия РТСТ, РТЛД: проверенные годами безаварийной эксплуатации токоограничивающие реакторы.',
    'RTST, RTLD series: current-limiting reactors proven by years of trouble-free operation.', 'reactors'),
  P('2.6.2', 'Шунтирующие реакторы (РТОС, РОЛД)', 'Shunt reactors (RTOS, ROLD)',
    'Серия РТОС, РОЛД: шунтирующие реакторы для сетей и подстанций.',
    'RTOS, ROLD series: shunt reactors for networks and substations.', 'reactors'),
  P('2.6.3', 'Фильтровые реакторы (РФСТ, РФОС)', 'Filter reactors (RFST, RFOS)',
    'Серия РФСТ, РФОС: фильтровые реакторы для сетей с нелинейными нагрузками.',
    'RFST, RFOS series: filter reactors for networks with non-linear loads.', 'reactors'),
  P('2.6.4', 'Демпфирующие реакторы', 'Damping reactors',
    'Демпфирующие реакторы для подавления резонансных и переходных явлений в сетях.',
    'Damping reactors for suppressing resonance and transient phenomena in networks.', 'reactors'),
  P('2.6.5', 'Реакторы/дроссели КРМ', 'KRM reactors/chokes',
    'Реакторы и дроссели для конденсаторных установок компенсации реактивной мощности.',
    'Reactors and chokes for reactive power compensation capacitor units.', 'reactors'),

  P('2.7.1', 'Дизельные погрузчики', 'Diesel forklifts',
    'Вилочные дизельные погрузчики различных грузоподъёмностей для складов и открытых площадок.',
    'Diesel forklifts of various capacities for warehouses and outdoor yards.', 'forklifts'),
  P('2.7.2', 'Газобензиновые погрузчики', 'LPG/petrol forklifts',
    'Погрузчики на сжиженном газе и бензине — универсальное решение для склада и производства.',
    'LPG and petrol forklifts — a universal solution for warehouses and production.', 'forklifts'),
  P('2.7.3', 'Электрические погрузчики', 'Electric forklifts',
    'Электрические вилочные погрузчики для работы в закрытых помещениях и на производственных площадках.',
    'Electric forklifts for indoor facilities and production sites.', 'forklifts'),
  P('2.7.4', 'Штабелеры', 'Stackers',
    'Штабелеры для складирования паллет на разных высотах.',
    'Stackers for pallet storage at different heights.', 'forklifts'),
  P('2.7.5', 'Ричтраки', 'Reach trucks',
    'Ричтраки для работы в узких проходах высотных складов.',
    'Reach trucks for narrow-aisle high-bay warehouses.', 'forklifts'),
  P('2.7.6', 'Транспортировщики паллет', 'Pallet trucks',
    'Электропогрузчики-транспортировщики паллет для перемещения грузов по складу.',
    'Electric pallet trucks for moving loads inside the warehouse.', 'forklifts'),
  P('2.7.7', 'Комплектовщики заказов', 'Order pickers',
    'Техника для комплектации заказов: высотные и низкорамные комплектовщики.',
    'Order picking equipment: high-level and low-level pickers.', 'forklifts'),
  P('2.7.8', 'Электрические тягачи', 'Electric tow tractors',
    'Электрические тягачи для перемещения тележек и прицепов.',
    'Electric tow tractors for moving carts and trailers.', 'forklifts'),
  P('2.7.9', 'Экскаваторы', 'Excavators',
    'Малые и средние экскаваторы из каталога складской и строительной техники.',
    'Small and medium excavators from our warehouse & construction equipment catalog.', 'forklifts'),

  P('2.8.1', 'Запчасти промышленного оборудования', 'Industrial equipment spare parts',
    'Запасные части для промышленного оборудования: подшипники, уплотнения, приводы.',
    'Spare parts for industrial equipment: bearings, seals, drives.', 'parts'),
  P('2.8.2', 'Запчасти автомобилей', 'Automotive spare parts',
    'Автомобильные запасные части, включая подшипники для автомобильной отрасли.',
    'Automotive spare parts, including bearings for the automotive industry.', 'parts'),
  P('2.8.3', 'Запчасти на складскую технику', 'Warehouse machinery spare parts',
    'Запчасти для погрузчиков, штабелеров и ричтраков, шины и компоненты.',
    'Spare parts for forklifts, stackers and reach trucks, tyres and components.', 'parts'),
  P('2.8.4', 'Аккумуляторные батареи', 'Battery packs',
    'Аккумуляторные батареи для складской техники, транспорта и систем резервного питания.',
    'Battery packs for warehouse machinery, vehicles and backup power systems.', 'parts'),
  P('2.8.5', 'Шины', 'Tyres',
    'Индустриальные, цельнолитые и пневматические шины, шины для сельхозтехники.',
    'Industrial, solid and pneumatic tyres, tyres for agricultural machinery.', 'parts'),
  P('2.8.6', 'Расходные материалы', 'Consumables',
    'Фильтры воздушные, масляные и гидравлические.',
    'Air, oil and hydraulic filters.', 'parts'),

  P('2.9.1', 'Моторные и трансмиссионные масла', 'Engine & transmission oils',
    'Моторные и трансмиссионные масла для техники и оборудования.',
    'Engine and transmission oils for machinery and equipment.', 'fluids'),
  P('2.9.2', 'Гидравлические масла', 'Hydraulic oils',
    'Гидравлические масла для систем гидравлики промышленной и складской техники.',
    'Hydraulic oils for hydraulic systems of industrial and warehouse machinery.', 'fluids'),
  P('2.9.3', 'Индустриальные масла', 'Industrial oils',
    'Турбинные, редукторные и компрессорные масла для промышленного оборудования.',
    'Turbine, gear and compressor oils for industrial equipment.', 'fluids'),
  P('2.9.4', 'Охлаждающие жидкости', 'Coolants',
    'Охлаждающие жидкости для двигателей и промышленного оборудования.',
    'Coolants for engines and industrial equipment.', 'fluids'),
  P('2.9.5', 'Технологические смазки', 'Technical greases',
    'Технологические смазки для узлов трения оборудования.',
    'Technical greases for equipment friction units.', 'fluids'),
];

const materials = [
  { code: 'ГРЩК 220', title_ru: 'ГРЩК 220', title_en: 'GRRK 220', std: 'По ГОСТ 14192-97, IEC 60076-19-1, IEC 62271-200' },
  { code: 'РУ-10К', title_ru: 'Распределительное устройство РУ-10К', title_en: 'Power distribution unit RU-10K', std: 'По ГОСТ 14192-97, IEC 60076-19-1, IEC 62271-200' },
  { code: 'ШКМ 3,5', title_ru: 'Сетевой трансформатор ШКМ 3,5', title_en: 'Grid transformer SHKM 3.5', std: 'По ГОСТ 14192-97, IEC 60076-19-1, IEC 62271-200' },
  { code: 'УКМ / УКМФ', title_ru: 'Конденсаторная установка УКМ / УКМФ', title_en: 'Capacitor unit UKM / UKMF', std: 'По ГОСТ 14192-97, IEC 60076-19-1, IEC 62271-200' },
  { code: 'УЗР-3,5', title_ru: 'Устройство защитное УЗР-3,5', title_en: 'Protection device UZR-3.5', std: 'По ГОСТ 14192-97, IEC 60076-19-1, IEC 62271-200' },
  { code: 'БСК15', title_ru: 'Батарея статических конденсаторов БСК15', title_en: 'Static capacitor bank BSK15', std: 'По ГОСТ 14192-97, IEC 60076-19-1, IEC 62271-200' },
  { code: 'УЗОС', title_ru: 'Устройство защиты УЗОС', title_en: 'Protection device UZOS', std: 'По ГОСТ 14192-97, IEC 60076-19-1, IEC 62271-200' },
  { code: 'ФТКМ', title_ru: 'Фильтр токоограничивающий ФТКМ', title_en: 'Current-limiting filter FTKM', std: 'По ГОСТ 14192-97, IEC 60076-19-1, IEC 62271-200' },
];

const services = [
  {
    num: '4.1', title_ru: 'Информационные технологии', title_en: 'Information technology',
    body_ru: '', body_en: '',
    list_ru: [
      'Технологии искусственного интеллекта',
      'Web-разработка',
      'QA и сервисная поддержка',
      'Аутстаффинг разработчиков',
      'Поставка серверного оборудования',
    ],
    list_en: [
      'Artificial intelligence technologies',
      'Web development',
      'QA & service support',
      'Developer staff augmentation',
      'Server equipment supply',
    ],
  },
  {
    num: '4.2', title_ru: 'Научные исследования и разработка', title_en: 'Research & development',
    body_ru: 'Выполнение НИОКР и ОКР, в том числе разработка конструкторской, эксплуатационной и программной документации (КД, ЭД и ПД) по требованиям заказчика с соблюдением требований действующих стандартов и регламентов. Оформление документации по результатам исследований.',
    body_en: 'Execution of R&D and development work, including design, operating and software documentation to customer requirements in compliance with current standards and regulations. Documentation of research results.',
    list_ru: [], list_en: [],
  },
  {
    num: '4.3', title_ru: 'Пуско-наладочные работы', title_en: 'Commissioning',
    body_ru: 'Пусконаладка энергооборудования, систем компенсации реактивной мощности, преобразователей и средств автоматики.',
    body_en: 'Commissioning of power equipment, reactive power compensation systems, converters and automation.',
    list_ru: [], list_en: [],
  },
  {
    num: '4.4', title_ru: 'Расчёты и моделирование', title_en: 'Calculations & simulation',
    body_ru: 'Наши специалисты в совершенстве владеют передовыми инструментами цифрового моделирования: математическое и имитационное моделирование в электроэнергетике, расчёты на прочность и устойчивость металлоконструкций, конструкторские и инженерные расчёты, в том числе по выбору устройств компенсации реактивной мощности и фильтрации гармоник.',
    body_en: 'Our specialists master advanced digital simulation tools: mathematical and simulation modeling in power engineering, strength and stability calculations, design and engineering calculations, including selection of reactive power compensation and harmonic filtering devices.',
    list_ru: [], list_en: [],
  },
  {
    num: '4.5', title_ru: 'Энергетическое обследование', title_en: 'Energy audit',
    body_ru: '', body_en: '',
    list_ru: [
      'Исследования качества электрической энергии, тепловизионные обследования малых и больших объектов',
      'Выявление проблем в энергоснабжении и поиск путей их устранения',
      'Консультирование по организационно-техническим мероприятиям в области электроснабжения промышленных предприятий',
    ],
    list_en: [
      'Power quality studies, thermal imaging surveys of small and large facilities',
      'Detecting power supply problems and finding solutions',
      'Consulting on organizational and technical measures in power supply of industrial enterprises',
    ],
  },
  {
    num: '4.6', title_ru: 'Разработка технической документации', title_en: 'Technical documentation',
    body_ru: 'Разработка конструкторской, эксплуатационной и программной документации (КД, ЭД, ПД) в соответствии с требованиями стандартов.',
    body_en: 'Development of design, operating and software documentation in line with standards.',
    list_ru: [], list_en: [],
  },
  {
    num: '4.7', title_ru: 'Бухгалтерские услуги для Вашего бизнеса', title_en: 'Accounting services for your business',
    body_ru: '', body_en: '',
    list_ru: [
      'Ведение бухгалтерского и налогового учёта',
      'Обработка входящих первичных документов',
      'Подготовка документов для покупателей',
      'Подготовка и проведение платежей',
      'Учёт банковских и кассовых операций',
      'Сверка с контрагентами',
      'Подготовка отчётности ИФНС, Росстат и др.',
    ],
    list_en: [
      'Bookkeeping & tax accounting',
      'Processing incoming primary documents',
      'Preparing documents for customers',
      'Preparation and execution of payments',
      'Bank & cash transactions accounting',
      'Reconciliation with counterparties',
      'Reporting to IFNS, Rosstat, etc.',
    ],
  },
];

const contentDefaults = {
  home_hero: {
    kicker_ru: 'Научно-производственное объединение', kicker_en: 'Research & Production Association',
    title_ru: 'Компенсация реактивной мощности и надёжное энергооборудование',
    title_en: 'Reactive power compensation and reliable power equipment',
    subtitle_ru: 'Изготавливаем и поставляем энергооборудование от 230 В до 220 кВ, импортируем продукцию из дружественных стран и оказываем инженерные услуги — от расчётов до пусконаладки.',
    subtitle_en: 'We manufacture and supply power equipment from 230 V to 220 kV, import products from friendly countries and provide engineering services — from calculations to commissioning.',
  },
  about_intro: {
    badge_ru: 'Создано 17 марта 2023 г.', badge_en: 'Founded 17 March 2023',
    title_ru: 'Кто мы', title_en: 'Who we are',
    intro_ru: '17 марта 2023 г. было создано Научно-Производственное Объединение КИПРОЛ с целью выполнения работ по импортозамещению в РФ, а также импорту в РФ востребованной и качественной продукции из дружественных стран — для снижения рисков непоставки, а также для замены выбывающей продукции из недружественных стран в сфере энергетики.',
    intro_en: 'On 17 March 2023 the KIPROL Research & Production Association was founded to carry out import substitution in Russia and to import in-demand, quality products from friendly countries — reducing supply risks and replacing products withdrawn from the market in the energy sector.',
  },
  contacts: {
    phone: '+7 (927) 212-39-34',
    phone_href: 'tel:+79272123934',
    email: 'info@kiprol.ru',
    address_ru: 'Россия, Самарская область, г. Тольятти, 445045',
    address_en: 'Russia, Samara region, Tolyatti, 445045',
    hours_ru: 'Пн–Пт 7:00–17:00 МСК',
    hours_en: 'Mon–Fri 7:00–17:00 MSK',
    telegram_url: 'https://t.me/+ib13aD-uEgJlYmUy',
  },
  site: {
    topbar_ru: 'Пн–Пт 7:00–17:00 МСК  ·  +7 (927) 212-39-34  ·  info@kiprol.ru',
    topbar_en: 'Mon–Fri 7:00–17:00 MSK  ·  +7 (927) 212-39-34  ·  info@kiprol.ru',
    footer_ru: '© 2024 ТМ KIPROL.RU ‖ КИПРОЛ.РФ',
    footer_en: '© 2024 KIPROL.RU',
    telegram_url: 'https://t.me/+ib13aD-uEgJlYmUy',
  },
  materials,
  services,
};

module.exports = { categories, products, contentDefaults, materials, services };
